version: '3'

services:

  app:
    image: sonarqube:latest
    ports:
      - "80:9000"
    volumes:
      - data:/opt/sonarqube/data
      - conf:/opt/sonarqube/conf
      - extensions:/opt/sonarqube/extensions
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar

  db:
    image: postgres:latest
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar

volumes:
  data:
  conf:
  extensions:
  db: